/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BlinkMatchEscrow {
  export type MatchStruct = {
    creator: AddressLike;
    challenger: AddressLike;
    stakeToken: AddressLike;
    stakeAmount: BigNumberish;
    roomIdHash: BytesLike;
    createdAt: BigNumberish;
    startedAt: BigNumberish;
    resultHash: BytesLike;
    winner: AddressLike;
    status: BigNumberish;
  };

  export type MatchStructOutput = [
    creator: string,
    challenger: string,
    stakeToken: string,
    stakeAmount: bigint,
    roomIdHash: string,
    createdAt: bigint,
    startedAt: bigint,
    resultHash: string,
    winner: string,
    status: bigint
  ] & {
    creator: string;
    challenger: string;
    stakeToken: string;
    stakeAmount: bigint;
    roomIdHash: string;
    createdAt: bigint;
    startedAt: bigint;
    resultHash: string;
    winner: string;
    status: bigint;
  };
}

export interface BlinkMatchEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelExpiredMatch"
      | "createMatch"
      | "getMatch"
      | "joinExpiry"
      | "joinMatch"
      | "noShowExpiry"
      | "owner"
      | "referee"
      | "refundNoShow"
      | "renounceOwnership"
      | "resolveMatch"
      | "setReferee"
      | "startMatch"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCancelled"
      | "MatchCreated"
      | "MatchJoined"
      | "MatchRefunded"
      | "MatchResolved"
      | "MatchStarted"
      | "OwnershipTransferred"
      | "RefereeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelExpiredMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinExpiry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "noShowExpiry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "referee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundNoShow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMatch",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelExpiredMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinExpiry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "noShowExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundNoShow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setReferee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MatchCancelledEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    creator: AddressLike,
    stakeToken: AddressLike,
    stakeAmount: BigNumberish,
    roomIdHash: BytesLike
  ];
  export type OutputTuple = [
    matchId: bigint,
    creator: string,
    stakeToken: string,
    stakeAmount: bigint,
    roomIdHash: string
  ];
  export interface OutputObject {
    matchId: bigint;
    creator: string;
    stakeToken: string;
    stakeAmount: bigint;
    roomIdHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchJoinedEvent {
  export type InputTuple = [matchId: BigNumberish, challenger: AddressLike];
  export type OutputTuple = [matchId: bigint, challenger: string];
  export interface OutputObject {
    matchId: bigint;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchRefundedEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResolvedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    loser: AddressLike,
    resultHash: BytesLike
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    loser: string,
    resultHash: string
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    loser: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchStartedEvent {
  export type InputTuple = [matchId: BigNumberish, startedAt: BigNumberish];
  export type OutputTuple = [matchId: bigint, startedAt: bigint];
  export interface OutputObject {
    matchId: bigint;
    startedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefereeUpdatedEvent {
  export type InputTuple = [referee: AddressLike];
  export type OutputTuple = [referee: string];
  export interface OutputObject {
    referee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlinkMatchEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BlinkMatchEscrow;
  waitForDeployment(): Promise<this>;

  interface: BlinkMatchEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelExpiredMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMatch: TypedContractMethod<
    [stakeToken: AddressLike, stakeAmount: BigNumberish, roomIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [BlinkMatchEscrow.MatchStructOutput],
    "view"
  >;

  joinExpiry: TypedContractMethod<[], [bigint], "view">;

  joinMatch: TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;

  noShowExpiry: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referee: TypedContractMethod<[], [string], "view">;

  refundNoShow: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveMatch: TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setReferee: TypedContractMethod<
    [newReferee: AddressLike],
    [void],
    "nonpayable"
  >;

  startMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelExpiredMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [stakeToken: AddressLike, stakeAmount: BigNumberish, roomIdHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [BlinkMatchEscrow.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinExpiry"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "joinMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "noShowExpiry"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundNoShow"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReferee"
  ): TypedContractMethod<[newReferee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MatchCancelled"
  ): TypedContractEvent<
    MatchCancelledEvent.InputTuple,
    MatchCancelledEvent.OutputTuple,
    MatchCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchJoined"
  ): TypedContractEvent<
    MatchJoinedEvent.InputTuple,
    MatchJoinedEvent.OutputTuple,
    MatchJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MatchRefunded"
  ): TypedContractEvent<
    MatchRefundedEvent.InputTuple,
    MatchRefundedEvent.OutputTuple,
    MatchRefundedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResolved"
  ): TypedContractEvent<
    MatchResolvedEvent.InputTuple,
    MatchResolvedEvent.OutputTuple,
    MatchResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MatchStarted"
  ): TypedContractEvent<
    MatchStartedEvent.InputTuple,
    MatchStartedEvent.OutputTuple,
    MatchStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefereeUpdated"
  ): TypedContractEvent<
    RefereeUpdatedEvent.InputTuple,
    RefereeUpdatedEvent.OutputTuple,
    RefereeUpdatedEvent.OutputObject
  >;

  filters: {
    "MatchCancelled(uint256)": TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;
    MatchCancelled: TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;

    "MatchCreated(uint256,address,address,uint256,bytes32)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchJoined(uint256,address)": TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;
    MatchJoined: TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;

    "MatchRefunded(uint256)": TypedContractEvent<
      MatchRefundedEvent.InputTuple,
      MatchRefundedEvent.OutputTuple,
      MatchRefundedEvent.OutputObject
    >;
    MatchRefunded: TypedContractEvent<
      MatchRefundedEvent.InputTuple,
      MatchRefundedEvent.OutputTuple,
      MatchRefundedEvent.OutputObject
    >;

    "MatchResolved(uint256,address,address,bytes32)": TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;
    MatchResolved: TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;

    "MatchStarted(uint256,uint64)": TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;
    MatchStarted: TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefereeUpdated(address)": TypedContractEvent<
      RefereeUpdatedEvent.InputTuple,
      RefereeUpdatedEvent.OutputTuple,
      RefereeUpdatedEvent.OutputObject
    >;
    RefereeUpdated: TypedContractEvent<
      RefereeUpdatedEvent.InputTuple,
      RefereeUpdatedEvent.OutputTuple,
      RefereeUpdatedEvent.OutputObject
    >;
  };
}
